### ISSUE TITLE
the new update makes it keep showing this error

### ISSUE THREAD

**Issue by BBBABUHS** [LaneSh4d0w/query-streamlink#22]
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

https://leongzhang692198.herokuapp.com/iptv-query?streaming-ip=https://www.vidio.com/live/204-sctv

**Comment by BBBABUHS** [comment]
2022-07-24T06:21:35.573055+00:00 app[web.1]: [2022-07-24 06:21:35,572] error in app: Exception on /iptv-query [GET]
2022-07-24T06:21:35.573067+00:00 app[web.1]: Traceback (most recent call last):
2022-07-24T06:21:35.573067+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
2022-07-24T06:21:35.573067+00:00 app[web.1]:     response = self.full_dispatch_request()
2022-07-24T06:21:35.573068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
2022-07-24T06:21:35.573068+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2022-07-24T06:21:35.573069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
2022-07-24T06:21:35.573069+00:00 app[web.1]:     rv = self.dispatch_request()
2022-07-24T06:21:35.573069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
2022-07-24T06:21:35.573070+00:00 app[web.1]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-07-24T06:21:35.573070+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask_limiter/extension.py", line 1115, in __inner
2022-07-24T06:21:35.573071+00:00 app[web.1]:     R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
2022-07-24T06:21:35.573071+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask_limiter/extension.py", line 1115, in __inner
2022-07-24T06:21:35.573071+00:00 app[web.1]:     R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
2022-07-24T06:21:35.573072+00:00 app[web.1]:   File "/app/main.py", line 44, in home
2022-07-24T06:21:35.573072+00:00 app[web.1]:     response = query_handler(request.args)
2022-07-24T06:21:35.573073+00:00 app[web.1]:   File "/app/main.py", line 28, in query_handler
2022-07-24T06:21:35.573073+00:00 app[web.1]:     return get_streams(args.get("streaming-ip")) if valid else "The URL you've entered is not valid."
2022-07-24T06:21:35.573074+00:00 app[web.1]:   File "/app/api.py", line 17, in get_streams
2022-07-24T06:21:35.573075+00:00 app[web.1]:     return link.to_url() if ("live" not in quality or "best" in quality) and "chunklist" in link.to_url() or "live" in quality and "best" not in quality else link.to_manifest_url()
2022-07-24T06:21:35.573075+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/streamlink/stream/stream.py", line 49, in to_manifest_url
2022-07-24T06:21:35.573076+00:00 app[web.1]:     raise TypeError(f"<{self.__class__.__name__} [{self.shortname()}]> cannot be translated to a manifest URL")
2022-07-24T06:21:35.573076+00:00 app[web.1]: TypeError: <DASHStream [dash]> cannot be translated to a manifest URL
2022-07-24T06:21:35.573954+00:00 app[web.1]: 10.1.20.202 - - [24/Jul/2022:06:21:35 +0000] "GET /iptv-query?streaming-ip=https://www.vidio.com/live/204-sctv HTTP/1.1" 500 265 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"

**Comment by LaneSh4d0w** [comment]
> 2022-07-24T06:21:35.573055+00:00 app[web.1]: [2022-07-24 06:21:35,572] error in app: Exception on /iptv-query [GET]
> 2022-07-24T06:21:35.573067+00:00 app[web.1]: Traceback (most recent call last):
> 2022-07-24T06:21:35.573067+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
> 2022-07-24T06:21:35.573067+00:00 app[web.1]:     response = self.full_dispatch_request()
> 2022-07-24T06:21:35.573068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
> 2022-07-24T06:21:35.573068+00:00 app[web.1]:     rv = self.handle_user_exception(e)
> 2022-07-24T06:21:35.573069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
> 2022-07-24T06:21:35.573069+00:00 app[web.1]:     rv = self.dispatch_request()
> 2022-07-24T06:21:35.573069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
> 2022-07-24T06:21:35.573070+00:00 app[web.1]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
> 2022-07-24T06:21:35.573070+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask_limiter/extension.py", line 1115, in __inner
> 2022-07-24T06:21:35.573071+00:00 app[web.1]:     R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
> 2022-07-24T06:21:35.573071+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/flask_limiter/extension.py", line 1115, in __inner
> 2022-07-24T06:21:35.573071+00:00 app[web.1]:     R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
> 2022-07-24T06:21:35.573072+00:00 app[web.1]:   File "/app/main.py", line 44, in home
> 2022-07-24T06:21:35.573072+00:00 app[web.1]:     response = query_handler(request.args)
> 2022-07-24T06:21:35.573073+00:00 app[web.1]:   File "/app/main.py", line 28, in query_handler
> 2022-07-24T06:21:35.573073+00:00 app[web.1]:     return get_streams(args.get("streaming-ip")) if valid else "The URL you've entered is not valid."
> 2022-07-24T06:21:35.573074+00:00 app[web.1]:   File "/app/api.py", line 17, in get_streams
> 2022-07-24T06:21:35.573075+00:00 app[web.1]:     return link.to_url() if ("live" not in quality or "best" in quality) and "chunklist" in link.to_url() or "live" in quality and "best" not in quality else link.to_manifest_url()
> 2022-07-24T06:21:35.573075+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/streamlink/stream/stream.py", line 49, in to_manifest_url
> 2022-07-24T06:21:35.573076+00:00 app[web.1]:     raise TypeError(f"<{self.__class__.__name__} [{self.shortname()}]> cannot be translated to a manifest URL")
> 2022-07-24T06:21:35.573076+00:00 app[web.1]: TypeError: <DASHStream [dash]> cannot be translated to a manifest URL
> 2022-07-24T06:21:35.573954+00:00 app[web.1]: 10.1.20.202 - - [24/Jul/2022:06:21:35 +0000] "GET /iptv-query?streaming-ip=https://www.vidio.com/live/204-sctv HTTP/1.1" 500 265 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"

There's something I've seen only once, and my implementation weirdly works at night only.

**Comment by BBBABUHS** [comment]
https://leongzhang692198.herokuapp.com/iptv-query?streaming-ip=https://www.vidio.com/live/204-sctv
try and see

**Comment by LaneSh4d0w** [comment]
I've released a fix that made sure DASH streams work. I've retested this link, works now fine.
